### ISSUE TITLE
Karaken2 installation issue

### ISSUE THREAD

**Issue by ellango85** [tobiasrausch/covid19#2]
Hi,
while downloading kraken2 database, I got an issue "
$ ./prepareDB.sh
mkdir: cannot create directory ‘humanDB’: File exists
Downloading nucleotide gb accession to taxon map... done.
Downloading nucleotide wgs accession to taxon map... done.
Downloaded accession to taxon map(s)
Downloading taxonomy tree data... done.
Uncompressing taxonomy data... done.
Untarring taxonomy tree data... done.
mv: replace 'assembly_summary.txt', overriding mode 0444 (r--r--r--)? y
rsync_from_ncbi.pl: unexpected FTP path (new server?) for https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/405/GCF_000001405.39_GRCh38.p13
Creating sequence ID to taxonomy ID map (step 1)...
No preliminary seqid/taxid mapping files found, aborting.
Database disk usage: 34G
After cleaning, database uses 4.0K

How to fix this issue

**Comment by tobiasrausch** [comment]
I think there is a solution for this issue in the kraken2 repo [#508](https://github.com/DerrickWood/kraken2/issues/508).

**Comment by ellango85** [comment]
I have fixed the issue. Thanks
